### PR TITLE
Found new bluetooth endpoint (fixes #12) and fixes #9

### LINKED ISSUE #9: alarms / timers description typo?
In the alarms and timers section you have

```
For alarms: status: 1 for set up and 2 for currently ringing.
For alarms: status: 1 for set up and 3 for currently ringing.
```

I assume that at least one of these is supposed to be timers?

### LINKED ISSUE #12: GET /setup/bluetooth/connect (not from your documentation) gives error 405
I was just goofing around trying out API calls that seemed plausible, and hit on this one which I assume requires a POST request.

### PR DESCRIPTION
**Pull request by yummypasta**
I haven't found a valid body to send, but I know a POST endpoint exists. By the endpoint name, I can guess it connects a new bluetooth device.

### CODE REVIEW

**Comment by yummypasta** [comment]
Fixes #9 and #12

**Comment by rithvikvibhu** [comment]
Just curious, where did you get the endpoint from?

**Comment by yummypasta** [comment]
@rithvikvibhu Just playing around with bluetooth endpoints. I guessed that there would have to be a connect endpoint.

**Comment by vaguerant** [comment]
Solved it.

It doesn't connect a new device, it sets the Home into the mode where it looks for devices that are already paired (i.e., the conventional behavior this is mirroring is a situation where you enable Bluetooth on a paired device but don't actually connect to the Home using that device, then say "Hey Google, connect to Bluetooth" and Google Home initiates the connection).

The request looks like the following:

**Headers**
```
Content-Type: application/json
```
**Body**
```
{
  "connect": true
}
```
Obviously, it also works for disconnecting from Bluetooth:
```
{
  "connect": false
}
```
Which is like saying "Hey Google, disconnect Bluetooth".

**Comment by rithvikvibhu** [comment]
Nice! So it's like making Home look for paired devices and initiating (and disconnecting) a connection.

**Comment by rithvikvibhu** [comment]
I couldn't reproduce this. Both of them returned `400 Bad Request`
Are you talking about `/setup/bluetooth/connect`?

**Comment by vaguerant** [comment]
That's odd. Yes, ```/setup/bluetooth/connect```. Is it possible you're doing something like putting "true" and "false" in quotes? There should be no quotes for true/false settings, as they're binary values, not strings, and including the quotes does cause a ```400 Bad Request```.

**Comment by rithvikvibhu** [comment]
Ha nice catch. I unpaired my phone to capture that request before trying this. It works now that I've paired it again.

**Pull request merged**
